### ISSUE TITLE
Can't make submodules: "This plugin requires cairo pango  glu gl"

### ISSUE THREAD

**Issue by unfa** [x42/sisco.lv2#10]
```
$  make submodules
Version: 0.7.0-2 -> 0 7 0 2
LV2 Version: 1793 5
Makefile:124: *** "This plugin requires cairo pango  glu gl".  Stop.
```

I guess I'm missing some dependencies?

**Comment by x42** [comment]
Looks like missing build-dependencies :  libpango-dev libcairo-dev, libgl1-mesa-dev (openGL package name may differ).   On debian based systems  `sudo apt-get build-dep x42-plugins` will get those.

**Comment by Schroedingberg** [comment]
For convenience of apt users: `sudo apt build-dep x42-plugins`

**Comment by x42** [comment]
I suggest to search the web for this error.

The Ubuntu Wiki has a long explanation, or you could find a quick hands-on solution like https://www.tecmint.com/fix-deb-src-uris-in-your-sources-list-error/


That being said, pretty much all GNU/Linux distros do package this plugin as part of `x42-plugins` package. There should be no need for casual users to compile it from source.
