### ISSUE TITLE
Porting to other platforms/formats (VST, AU)?

### ISSUE THREAD

**Issue by Kwurqx** [x42/sisco.lv2#13]
Stumbled upon this Oscilloscope (on a KVR Audio Forum). Look very usefull! Are there any plans to support other platforms/formats? Like VST? I bet the community would appreciate. I would.

**Comment by x42** [comment]
There are no plans to support non-free standards, sorry.

There are however some meta-plugins that can load LV2 and expose them as VST (e.g. Carla) and bridges (e.g. lv2vst).

Other platforms are supported, the plugin runs on Windows (XP or later), MacOS/X (10.5 and later), *BSD, GNU/Linux,...
