### ISSUE TITLE
Artifacts after 1.0 sine wave

### ISSUE THREAD

**Issue by mxmilkb** [x42/sisco.lv2#14]
The wave was clipping the display so i turned Amp. down a bit, but areas where that were drawn before don't get redrawn.

https://i.imgur.com/s7tTfQq.png

**Comment by x42** [comment]
Do you have a recipe how to reproduce this?
I guess there might be a specific sisco amp-gain setting or window height, I've tried a bit but didn't yet hit those values, yet.

**Comment by mxmilkb** [comment]
I just connected ZLFO to the scope

**Comment by x42** [comment]
got it thanks.
