### ISSUE TITLE
CV port varient?

### ISSUE THREAD

**Issue by mxmilkiib** [x42/sisco.lv2#20]
I'd like to request a straight CV port variant of sisco. Different to #15 because that was the context of signals above 1 and below -1. Having any kind of scope with CV ports would be handy compared to nothing.

**Comment by x42** [comment]
Unlikely going to happen. I still think using a float with a range outside -1..+1 for audio or CV is misguided.
Search the web for "What Every Computer Scientist Should Know About Floating-Point Arithmetic" by David Goldberg.

**Comment by mxmilkiib** [comment]
I'm not requesting a variant of the scope that represents values outside of -1 and 1 but for a variant that has CV input and output ports.

**Comment by mxmilkiib** [comment]
I made a https://aur.archlinux.org/packages/x42-sisco-cv-git
