### ISSUE TITLE
No time sweep in GTK

### ISSUE THREAD

**Issue by therealkitman** [x42/sisco.lv2#8]
Hi,

I compiled sisco.lv2 with the BUILDGTK?=yes in Makefile.

The resultant scope_gtk gui is displayed in Carla and ingen but there is no time sweep so no signal is captured. The x42-scope app though works fine in Carla and as a standalone via jack.

Not sure what other info to give you but happy to help with any follow up you require.

Regards,
Chris.

**Comment by blablack** [comment]
@therealkitman big big shot in the dark but could it be you need to activate the GUI update in Ingen?
I'm not in front of my computer at the moment, but from memory it's called "animate signal" or something?

It activates (or deactivate) most the GUI updates in Ingen to save on CPU...

**Comment by therealkitman** [comment]
Hi again,

I just created a new project in ingen that just has the scope. It is
Enabled in its context menu

The only warnings I get is -

(ingen:13727): Gdk-WARNING **: gdk_window_set_icon_list: icons too
large
Loaded 262 plugins

(ingen:13727): Gdk-WARNING **: gdk_window_set_icon_list: icons too
large

(ingen:13727): Gdk-WARNING **: gdk_window_set_icon_list: icons too
large

Regards,
Chris.

----- Original Message -----

**Comment by x42** [comment]
The gtk version is deprecated and will soon be removed. compile with
```
make EXTERNALUI=no
```
that will also result in an embeddable version.

**Comment by therealkitman** [comment]
Hi Robin and thanks,

I recompiled sisco as instructed. But a gui does not appear. I get
these two messages when I single click on "Embed GUI" in ingen.

Failed to create LV2 UI
Failed to create LV2 UI 

I tried adding some Calf plugins to test ingen - most of those plugins
show an embedded gui or an external one (some don't like Calf
Analyzer).

(ingen:5357): Gdk-WARNING **: gdk_window_set_icon_list: icons too
large
CALF DEBUG: instance (nil) data (nil)
Configuration not available because of lack of
instance-access/data-access
LV2 GUI already embedded, cannot pop up
CALF DEBUG: instance (nil) data (nil)
Configuration not available because of lack of
instance-access/data-access

(ingen:5357): Gdk-WARNING **: gdk_window_set_icon_list: icons too
large

Regards,
Chris.

----- Original Message -----

**Comment by x42** [comment]
calf are gtk plugins (they load in ingen as gtk host directly). with  externalui=no  sisco becomes a X11UI and ingen loads it via libsuil.  I have not tested ingen, but it works in jalv (identical LV2 handling as ingen)

can you try 

```
jalv.gtk http://gareus.org/oss/lv2/sisco#Mono
```

to track things down, information from
```
 lv2info http://gareus.org/oss/lv2/sisco#Mono
```
will be helpful

**Comment by therealkitman** [comment]
Ok.

For the first command I get a pop gui with a single button that says
"Close" -
lilv_world_add_plugin(): error: ... found in
file:///home/chris/.lv2/blop.lv2/
lilv_world_add_plugin(): error: ... and     
file:///usr/local/lib/lv2/blop.lv2/
lilv_world_add_plugin(): error: Duplicate plugin 
lilv_world_add_plugin(): error: ... found in
file:///home/chris/.lv2/blop.lv2/
lilv_world_add_plugin(): error: ... and     
file:///usr/local/lib/lv2/blop.lv2/
lilv_world_add_plugin(): error: Duplicate plugin 
lilv_world_add_plugin(): error: ... found in
file:///home/chris/.lv2/blop.lv2/
lilv_world_add_plugin(): error: ... and     
file:///usr/local/lib/lv2/blop.lv2/
lilv_world_add_plugin(): error: Duplicate plugin 
lilv_world_add_plugin(): error: .. found in
file:///home/chris/.lv2/blop.lv2/
lilv_world_add_plugin(): error: ... and     
file:///usr/local/lib/lv2/blop.lv2/
lilv_world_add_plugin(): error: Duplicate plugin 
lilv_world_add_plugin(): error: ... found in
file:///home/chris/.lv2/blop.lv2/
lilv_world_add_plugin(): error: ... and     
file:///usr/local/lib/lv2/blop.lv2/
Plugin:       http://gareus.org/oss/lv2/sisco#Mono
No appropriate UI found
JACK Name:    Simple Scope (Mono)
Cannot lock down 86605722 byte memory area (Cannot allocate memory)
Block length: 128 frames
MIDI buffers: 32768 bytes
Comm buffers: 529408 bytes
Update rate:  25.0 Hz

Exiting...
chris@linux-4qye:~/Downloads/sisco.lv2>

And for the second command -
lilv_world_add_plugin(): error: ... found in
file:///home/chris/.lv2/blop.lv2/
lilv_world_add_plugin(): error: ... and     
file:///usr/local/lib/lv2/blop.lv2/
lilv_world_add_plugin(): error: Duplicate plugin 
lilv_world_add_plugin(): error: ... found in
file:///home/chris/.lv2/blop.lv2/
lilv_world_add_plugin(): error: ... and     
file:///usr/local/lib/lv2/blop.lv2/
lilv_world_add_plugin(): error: Duplicate plugin 
lilv_world_add_plugin(): error: .. found in
file:///home/chris/.lv2/blop.lv2/
lilv_world_add_plugin(): error: ... and     
file:///usr/local/lib/lv2/blop.lv2/
lilv_world_add_plugin(): error: Duplicate plugin 
lilv_world_add_plugin(): error: ... found in
file:///home/chris/.lv2/blop.lv2/
lilv_world_add_plugin(): error: ... and     
file:///usr/local/lib/lv2/blop.lv2/
lilv_world_add_plugin(): error: Duplicate plugin 
lilv_world_add_plugin(): error: ... found in
file:///home/chris/.lv2/blop.lv2/
lilv_world_add_plugin(): error: .. and     
file:///usr/local/lib/lv2/blop.lv2/
http://gareus.org/oss/lv2/sisco#Mono

        Name:              Simple Scope (Mono)
        Class:             Plugin
        Author:            Robin Gareus
        Author Email:      mailto:robin@gareus.org
        Author Homepage:   http://gareus.org/
        Has latency:       no
        Bundle:           
file:///home/chris/.lv2/sisco.lv2/
        Binary:           
file:///home/chris/.lv2/sisco.lv2/sisco.so
        UIs:
                http://gareus.org/oss/lv2/sisco#ui_gl
                        Class: 
http://kxstudio.sf.net/ns/lv2ext/external-ui#Widget
                        Binary:
file:///home/chris/.lv2/sisco.lv2/siscoUI_gl.so
                        Bundle:
file:///home/chris/.lv2/sisco.lv2/
        Data URIs:        
file:///home/chris/.lv2/sisco.lv2/manifest.ttl
                          
file:///home/chris/.lv2/sisco.lv2/siscottl
        Required Features: http://lv2plug.in/ns/ext/urid#map
        Optional Features:
http://lv2plug.in/ns/lv2core#hardRTCapable
        Extension Data:   
http://lv2plug.in/ns/ext/state#interface
        Presets: 

        Port 0:
                Type:       
http://lv2plug.in/ns/ext/atom#AtomPort
                            
http://lv2plug.in/ns/lv2core#InputPort
                Symbol:      control
                Name:        Control
                Designation:
http://lv2plug.in/ns/lv2core#control

        Port 1:
                Type:       
http://lv2plug.in/ns/ext/atom#AtomPort
                            
http://lv2plug.in/ns/lv2core#OutputPort
                Symbol:      notify
                Name:        Notify
                Designation:
http://lv2plug.in/ns/lv2core#control

        Port 2:
                Type:       
http://lv2plug.in/ns/lv2core#AudioPort
                            
http://lv2plug.in/ns/lv2core#InputPort
                Symbol:      in
                Name:        In

        Port 3:
                Type:       
http://lv2plug.in/ns/lv2core#OutputPort
                            
http://lv2plug.in/ns/lv2core#AudioPort
                Symbol:      out
                Name:        Out
chris@linux-4qye:~/Downloads/sisco.lv2> 

Regards.... 
 

----- Original Message -----

**Comment by x42** [comment]
mmh. it's still an externalui (not an X11UI)

clean out the old:
```
## rm -rf ~/.lv2/sisco.lv2
## or simply back it up:
mv ~/.lv2/sisco.lv2 /tmp/sisco.old
```

then re-compile:
```
make clean
make externalui=no
```

and deploy 
```
##either
cp -a build ~/.lv2/sisco.lv2
## or
sudo make install externalui=no
```

**Comment by x42** [comment]
ps the relevant line from `lv2info` is

```
 Class:  http://kxstudio.sf.net/ns/lv2ext/external-ui#Widget
```

this sould be 

```
Class: Class:  http://lv2plug.in/ns/extensions/ui#X11UI
```

**Comment by therealkitman** [comment]
Getting warmer. I now have the scope in ingen but there is still no
time sweep/waveform. But audio is passing through the In/Out ports.

 

----- Original Message -----

**Comment by therealkitman** [comment]
Sorry but those lines means nothing to me (I'm not a programmer).

However, to maybe save some time perhaps you can advice of something
else. What I am trying to do is use the am2.lv2 plugins and sisco.lv2
to build a sound lab where I can monitor various ports/gates/triggers
etc, monitor the effect of envelopes and LFOs on signals and amps etc.
I tried Carla but it can't handle the am2.lv2. If I use amsynth or
alsa mod synth all I can see is the outputs in jack with x42-scope but
not the internal gates/triggers etc.

Can you recommend an engine in linux other than ingen or carla where I
can experiment?

Thanks.

----- Original Message -----

**Comment by therealkitman** [comment]
Also as well as having just a flatline, the X and Y position controls
have no effect on the lines. See attached image.

----- Original Message -----

**Comment by x42** [comment]
OK. I have updated to latest ingen (from svn) and can confirm it's broken there.

This is an ingen issue (event messages are not passed corectly from the DSP part to the GUI). I'll look into fixing ingen.

**Comment by therealkitman** [comment]
OK, thanks. 

----- Original Message -----

**Comment by x42** [comment]
Fixed in ingen just now (since svn revision 5780). sisco runs when using "right-click > Embedd".

There's still a bit more work needed to allow double-click (open separate window), but that's underway.
(patch http://paste.debian.net/317996/)

**Comment by therealkitman** [comment]
Thanks Robin.

So all I have to do is download again as per the ingen website's 
instructions and rebuild?

    |svn co http://svn.drobilla.net/lad/trunk drobillad|


Thanks,
Chris.

**Comment by x42** [comment]
yes,  though unless you're in a hurry maybe wait until it's fixed for good (external GUI view,...)

**Comment by x42** [comment]
fixed for good in ingen svn rev 5786 - http://dev.drobilla.net/changeset/5786

**Comment by therealkitman** [comment]
Downloaded ingen rev 5787 and now the scope is displaying as expected.

Thanks very much for your help.

Regards,
Chris.
