### ISSUE TITLE
window grabs focus when mouse is over it

### ISSUE THREAD

**Issue by magnetophon** [x42/sisco.lv2#9]
The i3 window manager has a keyboard shortcut that lets you toggle focus between the foating and the normal windows.
When the scope is floating and the mouse is over it, it won't release focus.

I know of no other program that does this.

This is whith the stand-alone jack version, not tested with other versions.

**Comment by x42** [comment]
Latest git?

Some other robtk plugins do explicily request focus (XKEYFOCUSGRAB) `robtk/pugl/pugl_x11.c`, but sisco.lv2 never did that.  I don't have an explanation.

Could you check with `xwininfo`  and maybe `xev`?

**Comment by magnetophon** [comment]
I'm not running the latest git.
Should I try that?

```
xwininfo: Window id: 0x3a00003 "Simple Scope (4 channel)"

  Absolute upper-left X:  336
  Absolute upper-left Y:  28
  Relative upper-left X:  2
  Relative upper-left Y:  0
  Width: 940
  Height: 556
  Depth: 24
  Visual: 0x85
  Visual Class: TrueColor
  Border width: 0
  Class: InputOutput
  Colormap: 0x3a00002 (not installed)
  Bit Gravity State: ForgetGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsViewable
  Override Redirect State: no
  Corners:  +336+28  -4+28  -4-216  +336-216
  -geometry 940x556-2+28
```

**Comment by magnetophon** [comment]
This got fixed at some point.  :)
